import Head from "next/head";
import { Inter } from "@next/font/google";
import { Flex, Heading } from "@chakra-ui/react";
import Header from "./components/Header";
import BalanceCard from "./components/BalanceCard";
import { History } from "./components/History";
import { AddTransaction } from "./components/AddTransaction";



export default function Home() {

  

  return (
    <>
      <Head>
        <title>Expense Tracker App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          bg={'#F7F7F7'}
          direction={"column"}
          alignItems={"center"}
          justifyContent={"center"}
          minH={"100vh"}
          fontFamily={"sans-serif"}
        >
        <Header />
        <BalanceCard />
        <History />
        <AddTransaction />
        </Flex>
      </main>
    </>
  );
}
